version: "3"
services:
  playground:
    build: .
    image: playground
    container_name: playground
    ports:
      - "15000:8888"
      - "5680:5678"
    volumes:
      - ./:/opt/project
    stdin_open: true
    tty: true
    environment:
      JUPYTER_TOKEN: ""
    command: >
      bash -c "
      jupyter notebook --allow-root --ip='*' --port=8888 --NotebookApp.password='' --NotebookApp.token=''
      "
